
export const provinciasScrap2 = {
    alava: 'vi',
    albacete: 'ab',
    alicante: 'a',
    almeria: 'al',
    'principado de asturias': 'as',
    avila: 'av',
    badajoz: 'ba',
    'islas baleares': 'pm',
    barcelona: 'b',
    burgos: 'bu',
    caceres: 'cc',
    cadiz: 'ca',
    cantabria: 's',
    castellon: 'cs',
    'ciudad real': 'cr',
    cordoba: 'cb',
    cuenca: 'cu',
    girona: 'gi',
    granada: 'gr',
    guadalajara: 'gu',
    gipuzkoa: 'ss',
    huelva: 'hu',
    huesca: 'h',
    jaen: 'j',
    'a coruna': 'c',
    'la rioja': 'lo',
    'gran canaria': 'lp',
    leon: 'le',
    lerida: 'll',
    lugo: 'l',
    'comunidad de madrid': 'm',
    malaga: 'ma',
    'region de murcia': 'mu',
    'comunidad foral de navarra': 'na',
    ourense: 'or',
    palencia: 'pa',
    pontevedra: 'po',
    salamanca: 'sa',
    segovia: 'sg',
    sevilla: 'se',
    soria: 'so',
    tarragona: 't',
    'tenerife': 'tf',
    teruel: 'te',
    toledo: 'to',
    valencia: 'v',
    valladolid: 'va',
    vizcaya: 'bi',
    zamora: 'za',
    zaragoza: 'z',
    ceuta: 'ce',
    melilla: 'me'
}

export const provincias = [
    'ALAVA',
    'ALBACETE',
    'ALICANTE',
    'ALMERÍA',
    'ASTURIAS',
    'ÁVILA',
    'BADAJOZ',
    'BARCELONA',
    'BURGOS',
    'CÁCERES',
    'CÁDIZ',
    'CANTABRIA',
    'CASTELLÓN',
    'CIUDAD REAL',
    'CÓRDOBA',
    'CORUÑA',
    'CUENCA',
    'GERONA',
    'GRANADA',
    'GUADALAJARA',
    'GUIPÚZCOA',
    'HUELVA',
    'HUESCA',
    'BALEARES',
    'JAÉN',
    'LEÓN',
    'LÉRIDA',
    'LUGO',
    'MADRID',
    'MÁLAGA',
    'MURCIA',
    'NAVARRA',
    'ORENSE',
    'PALENCIA',
    'PALMAS',
    'PONTEVEDRA',
    'RIOJA',
    'SALAMANCA',
    'SEGOVIA',
    'SEVILLA',
    'SORIA',
    'TARRAGONA',
    'TENERIFE',
    'TERUEL',
    'TOLEDO',
    'VALENCIA',
    'VALLADOLID',
    'VIZCAYA',
    'ZAMORA',
    'ZARAGOZA',
    'CEUTA',
    'MELILLA'
]

export const comunidades = [
    'ANDALUCÍA',
    'ARAGÓN',
    'ASTURIAS',
    'BALEARES',
    'CANARIAS',
    'CANTABRIA',
    'MANCHA',
    'LEÓN',
    'CATALUÑA',
    'VALENCIANA',
    'EXTREMADURA',
    'GALICIA',
    'RIOJA',
    'MADRID',
    'NAVARRA',
    'VASCO',
    'MURCIA',
    'CEUTA',
    'MELILLA'
]
